#######################################################################
#                          BlockBall                                  #
# 		            	   by Shynixn							      #
#######################################################################

# You can find the permissions at https://shynixn.github.io/BlockBall/build/html/gettingstarted/permissions.html#permissionlist

############################

# Debug settings

# This setting should only be turned on if debugging messages are intended which is not necessarry for production servers.

############################

debug: false

############################

# Data-collecting settings

# Settings to send anonymous stats to https://bstats.org/plugin/bukkit/BlockBall.
# As this does not have an impact on your BlockBall experience at all I would like you to set it on true as knowing that my
# plugin gets used by many server helps me focusing on new updates ;)

############################

metrics: true

############################

# Arena configuration settings

# Join your server and create an arena via the ingame commands.
# You can edit the automatically created arena_x.yml files afterwards.

############################

############################

# Messages settings

# Settings to adjust the messages

############################

messages:
  prefix: '&0&l[&f&lBall&0&l]&7 '
  state-sign-enabled: '&aJoin'
  state-sign-disabled: '&4Disabled'
  state-sign-running: '&1Running'
  no-permission-join-game: "&cYou do not have permission to join this game."
  no-permission-spectate-game: "&cYou do not have permission to spectate this game."

############################

# Database settings

# All player stats are stored in a local file by default.
# It is recommend to edit these settings when you are using a MySQL database
# and have got a bigger player-base.

############################

sql:
  enabled: false
  host: localhost
  port: 3306
  usessl: false
  database: ''
  username: ''
  password: ''

############################

# Game settings

# allow-server-linking: Enable this to allow linking via BungeeCord between other servers with BlockBall installed.

############################

game:
  allow-server-linking: false
  ignore-ticking-settings: false

############################

# Command settings

# Instead of setting the commands inside of the plugin.yml, I believe you should be able to customize
# the whole command by yourself. Name, description, permission customize it to your needs.

# global-join: Settings for the command to join games from any world on your server.
# global-leave: Settings for the command to leave games from any world on your server.

############################

global-join:
  enabled: true
  command: bbjoin
  useage: /<command> <game> <team>
  description: Join a game.
  permission: blockball.command.use
  permission-message: You don't have permission
global-spectate:
  enabled: true
  command: bbspectate
  useage: /<command> <game>
  description: Spectate a game.
  permission: blockball.command.use
  permission-message: You don't have permission
global-leave:
  enabled: true
  command: bbleave
  useage: /<command>
  description: Leaves current game.
  permission: blockball.command.use
  permission-message: You don't have permission

############################

# Security settings

# Settings to adjust the position of players.
# fallback-spawnpoint: Spawnpoint for players who try to spawn in an blockball field.

############################

security:
  fallback-spawnpoint:
    enabled: false
    world: 'world'
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
